### ISSUE TITLE
Adding "round" ability?

### ISSUE THREAD

**Issue by aegis72** [cubiq/ComfyUI_SimpleMath#1]
How hard would it be to add "round" ability to this node?

**Comment by cubiq** [comment]
INT out is automatically rounded

**Comment by aegis72** [comment]
Sorry, I was meaning a "round" function that could be independently called. I ended up figuring something out for my specific purpose, which was to prep an image for ControlNet to be divisible by 16...I ended up using a "floatunaryoperator" from ComfyMath: 
![image](https://github.com/cubiq/ComfyUI_SimpleMath/assets/118572301/ac9f8647-c734-4154-8e90-2873066869ee)

**Comment by aegis72** [comment]
Thanks for the response, BTW!

**Comment by cubiq** [comment]
Added Modulo math op.
(a-(a % 16)`
will give a number divisible by 16 or simply
`1000-(1000 % 16) = 992`

**Comment by aegis72** [comment]
perfect. this will solve my rigged spaghetti system and also makes it easier to change the multiple if i ever need to! Thanks a ton.

![image](https://github.com/cubiq/ComfyUI_SimpleMath/assets/118572301/34ed2455-a380-4da0-9736-12db85d09ed3)
